#!/bin/bash -e

set -x
set -e

cd $(dirname $0)/..

export GOPATH=$(pwd)/Godeps/_workspace:$(pwd)/gopath

PACKAGE=./gopath/src/$(<.package)

if [ ! -e ${PACKAGE} ]; then
    mkdir -p $(dirname $PACKAGE)
    ln -s $(pwd) $PACKAGE
fi

echo export GOPATH=$GOPATH

mkdir -p bin
go build -v -o bin/host-api
